language: cpp

compiler:
  - clang
  - gcc
os:
  - osx
  - linux
matrix:
  exclude:
    - os: linux
      compiler: clang
rvm:
  - 2.2
  
before_install:
  # update packages
  - cmake --version
  - gem install msgpack 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libtool ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzf cmake-3.3.2.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd cmake-3.3.2 && ./configure && make && sudo make install && cd .. ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://github.com/msgpack/msgpack-c/releases/download/cpp-1.2.0/msgpack-1.2.0.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzf msgpack-1.2.0.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd msgpack-1.2.0 && ./configure --prefix=/usr && make && sudo make install && cd .. ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install msgpack ; fi
  
     
before_script:  
  - cmake .

script:
  - make
  # - ./bin/fluent-test
